version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/streaming?useSSL=false
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=w5pbhhmg
    depends_on:
      - db
    volumes:
      - ./uploads:/app/uploads

  db:
    image: mysql:5.7
    environment:
      - MYSQL_DATABASE=streaming
      - MYSQL_ROOT_PASSWORD=w5pbhhmg
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./src/main/resources/db/schema.sql:/docker-entrypoint-initdb.d/schema.sql

volumes:
  mysql_data: 